default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tech_blog_develop_2
  host: localhost
  port: 5433
  username: apptest
  password: password1

# test:
#   <<: *default
#   database: app_postgres_test

production:
  <<: *default
  database: tech_blog
  username: app_postgres
  # password: <%= ENV['APP_POSTGRES_DATABASE_PASSWORD'] %>
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
